### ISSUE TITLE
Refactor System Contract to use New Function-Style Interface Definition

### ISSUE THREAD

**Issue by bytemaster** [EOSIO/eos#1974] opened 2018-03-29 21:34 UTC
- remove generic currency from eosio.system contract and instead use eosio.token contract to create and issue EOS tokens.

**Comment by moskvanaft** [comment] 2018-04-19 22:42
First part of this ticket is a duplicate of #2227 
Second part is duplicate of #1889

**Closed by moskvanaft** 2018-04-19 22:42 UTC
Labels: duplicate
