### ISSUE TITLE
Smoke tests have non-deterministic timing gaps

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#4144] opened 2018-06-15 18:49 UTC
While tracking down test failures for #4060 @cj-oci and @wanderingbort identified that failures seemed directly related to an unintended and non-deterministic gap in production during certain test scenarios.

logs from CI machine (located here for those with access: https://buildkite.com/EOSIO/eosio/builds/2167 ) indicated that between block 222 and 223 there was an unintentional 7.5 (**wrong** 6.5) second gap that also corresponds with the loss of a transaction and failure of the test.

The lost transaction is being addressed in another issue.

This issue is to 
 - [ ] identify the source of that unintended gap
 - [ ] eliminate the cause from the existing scenarios
 - [ ] author new scenario(s) that explicitly invoke the cause of the gap in order deterministically replicate the failure modes it exercises.

**Comment by wanderingbort** [comment] 2018-06-15 19:52
After more digging I think the production gap _may_ be exacerbating the real source of the non-determinism which is whether any node is in a `producing` mode when it receives the transaction. 

If a node receives the transaction while producing (either by RPC or P2P) then the test should pass because it can immediately include it in the block it signs and sends out.  

If all nodes receive the transaction while speculating then the test fails because of a bug found as part of #4145 

The 7.5 second gap makes it extremely likely that all nodes are "speculating" and therefore there is no way the transaction can arrive on a node while its producing.

So, to make this deterministic we need to simulate the 2 cases explicitly:  ensure that there is a producing node that will receive the transaction (maybe by direct submission) AND ensure that the network has only speculating producers when submitting the transaction (maybe by downing a producer and ensuring we broadcast the tx during the gap)

**Comment by brianjohnson5972** [comment] 2019-01-07 19:42
One thing that I noticed that was not mentioned above is that even though there is a 7.5 second window gap for block time,  there is only a 6.5 second difference in the log timestamps:

2921507ms thread-0   producer_plugin.cpp:290       on_incoming_block    ] Received block 002f0cf0ee542973... #222 @ 2018-06-15T15:48:41.500 signed by defproducerc [trxs: 0, lib: 174, conf: 0, latency: 8 ms]
...
2921509ms thread-0   net_plugin.cpp:1599           recv_block           ]  got block 222 from localhost:9877 - e3ce95c
2922380ms thread-0   net_plugin.cpp:2495           handle_message       ] got a packed transaction, cancel wait
...
2922382ms thread-0   net_plugin.cpp:1735           bcast_transaction    ] found trxid in local_trxs
2927510ms thread-0   net_plugin.cpp:2717           accepted_transaction ] signaled, id = 712d4026dc3c47e9f3751e9b55b139a68316b6f664fc33beb2b2124e9742a882
2927510ms thread-0   net_plugin.cpp:2722           applied_transaction  ] signaled, id = 712d4026dc3c47e9f3751e9b55b139a68316b6f664fc33beb2b2124e9742a882
2928002ms thread-0   net_plugin.cpp:2713           irreversible_block   ] signaled, id = 0000008a0da24e0418d9f30644429ab92867a08b49bb03773d2295ad8b481bfc
2928003ms thread-0   net_plugin.cpp:2704           accepted_block_heade ] signaled, id = 000000dfaf83394e86da00d8f64e56315f9e922e8ca5b120700c94da176415d0
2928003ms thread-0   net_plugin.cpp:2708           accepted_block       ] signaled, id = 000000dfaf83394e86da00d8f64e56315f9e922e8ca5b120700c94da176415d0
2928003ms thread-0   producer_plugin.cpp:1073      produce_block        ] Produced block 000000dfaf83394e... #223 @ 2018-06-15T15:48:48.000 signed by defproducera [trxs: 0, lib: 186, confirmed: 24]

**Comment by brianjohnson5972** [comment] 2019-01-08 18:31
I believe that this problem, identified in restart-scenarios-test-hard_replay, came out of a miscalculation.  Above the test talks about a 7.5 second gap, but it actually is a 6.5 second gap, the 0.5 second "gap" between every block and 6 seconds for the 12 blocks that defproducerd could not produce because Node03 was intentionally killed by the test).  So this was a falsely identified error in the midst of analyzing the real error in #4060 (or possibly #4145). So I am closing this issue.

**Closed by brianjohnson5972** 2019-01-08 18:31 UTC
