### ISSUE TITLE
EOSIO_ABI macro does not allow processing of other code account's actions

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#2875] opened 2018-05-09 13:38 UTC
The definition for the macro:
   void apply( uint64_t receiver, uint64_t code, uint64_t action ) { \
      auto self = receiver; \
      if( code == self ) { \
         TYPE thiscontract( self ); \
         switch( action ) { \
            EOSIO_API( TYPE, MEMBERS ) \
         } \
         /* does not allow destructor of thiscontract to run: eosio_exit(0); */ \
      } \
   } \

Only allows for processing actions that are for your code account, so it would not be able to handle an action sent as a notification. (So "eosio.token" "transfer" messages would not be able to be processed.  Need to add another macro that allows for processing other code's actions and need to convert one of the existing complex examples to use it (like proxy.cpp).

**Comment by tbfleming** [comment] 2018-05-09 14:07
Duplicate of #2647

**Closed** 2018-05-09 14:11 UTC
