### ISSUE TITLE
Using eosiocpp -g generated to an empty ABI file

### ISSUE THREAD

**Issue by eoline7** [EOSIO/eos#2053] opened 2018-04-03 06:32 UTC
I run the "eosiocpp -g currency.abi currency.hpp"
get currency.abi like this:
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-03T06:24:59",
  "types": [],
  "structs": [],
  "actions": [],
  "tables": []
}

currency.hpp copied from eosiolib/currency.hpp
What is going wrong?

**Comment by Lomect** [comment] 2018-04-03 06:37
you can try by .cpp.

**Comment by eoline7** [comment] 2018-04-03 07:35
.cpp is same result

**Comment by okluoquan** [comment] 2018-04-04 00:11
.hpp add code annotation will be ok

such as   //@abi action   and     //@abi table

don't know why.


//@abi action
   struct PACKED( set_owner ) {
      account_name owner;
      uint32_t     delay;
   };

   //@abi table
   struct config {
      config(){}
      constexpr static uint64_t key = N(config);
      account_name        owner = 0;
      uint32_t            delay = 0;
      uint32_t            next_id = 0;
   };

**Comment by navcsdev** [comment] 2018-04-05 09:01
@eoline7 I read the sample https://github.com/EOSIO/eos/blob/master/TUTORIAL.md
And I think you need to 
`EOSIO_ABI( currency, (create)(issue)(transfer) )`

**Comment by farhan19aug** [comment] 2018-04-18 08:15
Thanks @okluoquan  That work for me (Y)

**Comment by anantanandgupta** [comment] 2018-04-18 22:04
I am trying to build the included examples and there is no way it is generating the proper ABI file

```
// file eosio.bios.cpp

#include <eosio.bios.hpp>

EOSIO_ABI( eosio::bios, (setpriv)(setalimits)(setglimits)(setprods)(reqauth) )
```

now in terminal
```
$ eosiocpp -o eosio.bios.wast eosio.bios.cpp
$ eosiocpp -g eosio.bios.abi eosio.bios.cpp
```

and this is the contents of the ABI file
```
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-04-18T21:59:15",
  "types": [],
  "structs": [],
  "actions": [],
  "tables": [],
  "ricardian_clauses": []
}
```

please tell me what is wrong in there and how to correct the issue

**Comment by Codegnosis** [comment] 2018-05-01 11:53
@anantanandgupta I'm noticing the same issue. I'm also running eosiocpp -g  in the project source directory (after having built/installed the latest master branch as of this morning), on the existing example contracts, and it's generating the same "blank" abi file. Even the simple hello contract.

**Comment by farhan19aug** [comment] 2018-05-07 06:52
I'm having the same issue but it work fine with using @//abi action. eosio_abi is not working and because of that it generate always empty and all example smart contract use the eosio_abi.

**Comment by deba10106** [comment] 2018-05-28 02:09
nothing worked for me. My currency folder is inside contracts folder, not inside eos.bios. I also get empty abi file!

**Comment by Joelone** [comment] 2018-06-07 18:50
I had the same issue, moving my contract to eos/contracts/my_contract works for me.

**Comment by guoc1995** [comment] 2018-06-11 17:58
I have come into the same problem for empty abi file, have anyone solved the problem? Thanks!

**Comment by svenpohl** [comment] 2018-06-12 10:20
Same issue here - empty abi with "eosiocpp -g eosio.token.abi eosio.token.cpp" and "eosiocpp -g eosio.token.abi eosio.token.hpp" - no error message. Any solution?

**Comment by dominic-healid** [comment] 2018-06-26 01:36
What is the cause of this issue? I have tried all solutions mentioned but no luck.

**Comment by andriantolie** [comment] 2018-07-03 09:50
currency.hpp is no longer available so I'm going to close this issue. To be able to use eosiocpp, you need //@abi annotation and also EOSIO_ABI by the way.

**Closed by andriantolie** 2018-07-03 09:50 UTC

**Comment by andriantolie** [comment] 2018-07-03 09:52
And also eosio.token.abi is not generated by eosiocpp. It hasn't been annotated to support eosiocpp :)

**Comment by nejc-skerjanc** [comment] 2018-07-16 10:34
Is there anything new? eosiocpp still make empty .abi file on my node...

**Comment by dominic-healid** [comment] 2018-08-22 07:13
in my case the actions is the only field that is empty from the ABI file.

Any thoughts? 

```
{
  "____comment": "This file was generated by eosio-abigen. DO NOT EDIT - 2018-08-22T07:10:24",
  "version": "eosio::abi/1.0",
  "types": [],
  "structs": [{
      "name": "account",
      "base": "",
      "fields": [{
          "name": "balance",
          "type": "asset"
        }
      ]
    },{
      "name": "currency",
      "base": "",
      "fields": [{
          "name": "supply",
          "type": "asset"
        },{
          "name": "max_supply",
          "type": "asset"
        },{
          "name": "issuer",
          "type": "name"
        }
      ]
    }
  ],
  "actions": [],
  "tables": [{
      "name": "accounts",
      "index_type": "i64",
      "key_names": [
        "balance"
      ],
      "key_types": [
        "asset"
      ],
      "type": "account"
    },{
      "name": "stat",
      "index_type": "i64",
      "key_names": [
        "supply"
      ],
      "key_types": [
        "asset"
      ],
      "type": "currency"
    }
  ],
  "ricardian_clauses": [],
  "error_messages": [],
  "abi_extensions": []
}
```

**Comment by dominic-healid** [comment] 2018-08-22 07:44
thanks for the response @nejc-skerjanc 

Actually what I did, I manually added the entries for the actions field however I'm still getting an error that says. 

```
Error 3050000: action exception
Error Details:
Unknown action create in contract proposal
```

even I already have this on my abi file 

```
 "actions": [{
      "name": "transfer",
      "type": "transfer",
      "ricardian_contract": ""
    },{
      "name": "issue",
      "type": "issue",
      "ricardian_contract": ""
    }, {
      "name": "create",
      "type": "create",
      "ricardian_contract": ""
}]
```
