### ISSUE TITLE
My wallet is already unclock ,but show "Error 3120006: No available wallet"

### ISSUE THREAD

**Issue by amActiveHello** [EOSIO/eos#5247] opened 2018-08-15 08:53 UTC
![image](https://user-images.githubusercontent.com/11773000/44140025-792a7a42-a0ab-11e8-827e-ea4de8f8004a.png)

**Comment by wanderingbort** [comment] 2018-08-15 11:08
duplicate of #5250 see that issue for resolution

**Closed by wanderingbort** 2018-08-15 11:08 UTC
