### ISSUE TITLE
eosd fails to produce block

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#429] opened 2017-09-14 05:58 UTC
Took the latest repository and built it.

Ran the following commands:

programs/launcher/launcher -n 2 -p 2
cd programs/eosc/
./eosc wallet create
./eosc wallet import 5Jt613UZhNhqFQU1AepQdYGpFTjhxxqLLTKphyjaiq87ttvxTJZ
./eosc wallet import "5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3"
./eosc create account inita hello EOS89cRtN4kh2pW1fE2KygSvxn3KJyZBLzNQ7cM12aG6WmRGuR726 EOS6iuq68qZTDF9HfCyFLaQoLmH6smYhWGugEPS1c9gic2eM6gS18
./eosc set contract hello ../../hello/hello.wast ../../hello/hello.abi

See the following output in stderr.txt (eosd output files).

3234004ms thread-0   producer_plugin.cpp:199       block_production_loo ] Got exception while generating block:
10 assert_exception: Assert Exception
itr != index.end():
    {}
    thread-0  chain_controller.cpp:112 get_recent_transaction

**Comment by brianjohnson5972** [comment] 2017-09-14 16:02
I get the same with just running ./eosd (not a multi-node problem)

**Comment by asvirido** [comment] 2017-09-19 11:32
How to fix that error? Please Help!!!

**Comment by heifner** [comment] 2017-09-19 21:00
Summary: This can be ignored for now.

This is caused by net_plugin::broadcast_block which is called by producer_plugin::maybe_produce_block.  The broadcast_block is trying to find a transaction via the chain and is failing to find it. This only affects block broadcast to other nodes and can be safely ignored for now. net_plugin broadcasting (P2P) is under active development under umbrella issue #291 which is scheduled for EOS Dawn 2.0.  Once #291 is complete we should verify that this no longer is an issue.

I've marked it Blocked by #291.

**Comment by heifner** [comment] 2017-11-13 22:15
Fixed by other P2P fixes.

**Closed by heifner** 2017-11-13 22:15 UTC
Labels: bug
