### ISSUE TITLE
Update upstream WAVM code

### ISSUE THREAD

**Issue by Vesnica** [EOSIO/eos#1579] opened 2018-03-07 10:45 UTC
WAVM fixed a issue recently which failed to process some wast files: https://github.com/AndrewScheidecker/WAVM/issues/65

I encounter the same error when trying to use eosioc to deploy wast files which produced by Rust and binaryen, WAVM's author fixed it very quickly, I hope eosio can merge the upstream so that I can use Rust to develop smart contract.

**Comment by spoonincode** [comment] 2018-03-11 06:07
Unfortunately this is nontrivial since upstream now requires LLVM5 or 6. Our ABI generator still only compiles with LLVM 4 (technically, Clang4). So to match upstream we either
1) fix ABI generator to work with Clang 5 & 6, I don't know how hard this would be
2) Require 4 "compilers" to build eosiod (the current of 3 is already too complex for many to grok)
or 3) modify upstream'ed WAVM to still work with LLVM4 (no thanks)

As a work around, eosioc will accept binary WASM; and binary WASM is what is stored in the chain. So if your toolchain generates valid binary WASM it really shouldn't matter that our WAST parser is outdated; just give eosioc the binary WASM. I've done this myself when using a clang6 wasm toolchain.

**Comment by spoonincode** [comment] 2018-03-11 06:18
ah I just saw that the error in the WAST parsing was due to call_indrect. I thought I fixed that in #1366. Are you sure you're running on master and not 2.0?

Also does rust use a lot of call_indirects? I would be curious if you could share some sample wasms if you have some readily available. I have limited the number of call_indirects available to contracts because of their resource consumption. But the number was quite arbitrary.

**Comment by Vesnica** [comment] 2018-03-11 07:06
- I'm using the SuperDawn-2018-03-04 branch
- Sample wasm and wast files can be found in https://github.com/AndrewScheidecker/WAVM/issues/65

eosioc's help did say it accept WAST or WASM files:
```
./eosioc set contract
ERROR: RequiredError: account
Create or update the contract on an account
Usage: ./eosioc set contract [OPTIONS] account wast-file [abi-file]

Positionals:
  account TEXT                The account to publish a contract for
  wast-file TEXT              The file containing the contract WAST or WASM
  abi-file TEXT               The ABI for the contract
```
But it output error when I give it wasm:
```
./eosioc set contract -a ~/code/empty.abi currency ~/code/wasm_test.gc.wasm
Reading WAST...
Assembling WASM...
Error parsing WebAssembly text file:
:1:1: expected '('
asm@
`_
^

```

**Comment by spoonincode** [comment] 2018-03-11 16:50
* Binary WASM for eosioc fixed in PR #1617 thanks
* The `call_indirect` syntax was fixed in master a while back via PR #1366. I've confirmed wasm_test.gc.wast does not throw a parsing error on master. Superdawn is based on older 2.0 branch so does not have this fix.

I think I'm going to go ahead and close this particular issue as both defects reported have been resolved.

**Closed by spoonincode** 2018-03-11 16:50 UTC

**Comment by spoonincode** [comment] 2018-03-11 16:54
By the way, that WASM might have some _weird_ problems on superdawn because it asks for 1.064MB of memory.

**Comment by Vesnica** [comment] 2018-03-12 00:47
Thank you, I'll check it out.
