### ISSUE TITLE
unlinkable_block_exception: Unlinkable block

### ISSUE THREAD

**Issue by csquan** [EOSIO/eos#6141] opened 2018-10-25 03:51 UTC
unlinkable_block_exception: Unlinkable block,then eos crush.
why?

**Comment by jgiszczak** [comment] 2018-10-25 18:58
The only known cause of unlinkable blocks in the current release is bnet_plugin.  Use net_plugin instead.

**Comment by csquan** [comment] 2018-10-26 01:45
you mean in config.ini,use net_plugin instead of bnet_plugin?

**Comment by andriantolie** [comment] 2018-10-26 03:06
Yes, in your config.ini, use
```
p2p-peer-address = 
```
instead of
```
bnet-connect = 
```
to connect to your peer. Make sure you input the net_plugin endpoint of your peer instead of bnet_plugin endpoint of your peer when you fill the config.ini.

net_plugin should be enabled by default in nodeos, so you don't need to explicitly state it in the config.ini

**Comment by csquan** [comment] 2018-10-26 03:15
yes,I have already done this before unlink show.

**Comment by wanderingbort** [comment] 2018-10-26 07:28
@csquan are there any log messages before the `unlinkable_block_exception` in the log.  Peers on the p2p network will still send you blocks even if you fail to validate one of them.  Failing creates a gap which makes all the newly learned blocks "unlinkable" 

There may be a root cause of the unlinkable blocks before them in the logs

**Comment by jgiszczak** [comment] 2018-11-19 21:35
Closed as no further reply. If you still have the same problem please ask https://eosio.stackexchange.com/ .

**Closed by jgiszczak** 2018-11-19 21:35 UTC
Labels: Support
