### ISSUE TITLE
docker run --name nodeos        err

### ISSUE THREAD

**Issue by 350054665** [EOSIO/eos#5741] opened 2018-09-19 08:29 UTC
2018-09-19T08:27:37.914 thread-0   main.cpp:136                  main                 ] Throw location unknown (consider using BOOST_THROW_EXCEPTION)
Dynamic exception type: boost::exception_detail::clone_impl<boost::exception_detail::error_info_injector<boost::program_options::unknown_option> >
std::exception::what: unrecognised option 'wallet-dir'

**Comment by firesWu** [comment] 2018-09-19 09:36
you should remove it in config.ini.
This is the update of 1.3.0.

Unknown configuration items in config.ini will now error on startup (#5678)
Prior to 1.3.0 unknown configuration items in config.ini would be silently ignored. This behavior has been changed in 1.3.0 to an error that prevents startup of nodeos. Users with old auto-generated config.ini files may need to remove some options that are no longer available in nodeos for example `wallet-dir` or `unlock-timeout`

**Comment by jgiszczak** [comment] 2018-09-19 20:11
Duplicate of #5742.

**Closed by jgiszczak** 2018-09-19 20:11 UTC
Labels: Support
