### ISSUE TITLE
Authorize multiple users to arise errors?? eos version 1.0.1

### ISSUE THREAD

**Issue by shishi614** [EOSIO/eos#3995] opened 2018-06-10 02:28 UTC
cleos set account permission liontoken active '{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"liontable","permission":"active"},"weight":1},{"permission":{"actor":"eosio1","permission":"active"},"weight":1}]}' owner
Error 3050000: action exception
Error Details:
Invalid authority: {"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"liontable","permission":"active"},"weight":1},{"permission":{"actor":"eosio1","permission":"active"},"weight":1}],"waits":[]}

but one user is ok
cleos set account permission liontoken active '{"threshold":1,"keys":[],"accounts":[{"permission":{"actor":"liontable","permission":"active"},"weight":1}]}' owner
executed transaction: acffccd2663b4946c88b05408b9f275cee4a07b693b22bb48c851b69038b7b21  144 bytes  1099 us
#         eosio <= eosio::updateauth            {"account":"liontoken","permission":"active","parent":"owner","auth":{"threshold":1,"keys":[],"accou...
warning: transaction executed locally, but may not be confirmed by the network yet

thanks！！！

**Comment by wanderingbort** [comment] 2018-06-12 22:40
seems a dupe of #4040

**Closed by wanderingbort** 2018-06-12 22:40 UTC
