### ISSUE TITLE
how to read large amounts of data from multiindex ?

### ISSUE THREAD

**Issue by sivachaitanya** [EOSIO/eos#6089] opened 2018-10-22 04:43 UTC
I am building an application on EOS which will store millions of rows of data in the multi index table. And this data will be used by an Analytics layer for analysis, how can I efficiently retrieve this millions of records, Is there some kind of pattern or method I should follow, please advice ?

**Comment by jgiszczak** [comment] 2018-10-22 19:38
Duplicate of #6091 due to github issues.

**Closed by jgiszczak** 2018-10-22 19:38 UTC
