### ISSUE TITLE
Add updateauth and deleteauth command processing to eosc

### ISSUE THREAD

**Issue by brianjohnson5972** [EOSIO/eos#298] opened 2017-09-01 15:45 UTC
(Account History API has logic to support these messages, but currently it is untested)

**Comment by brianjohnson5972** [comment] 2017-09-13 12:04
Not sure if this needs to have a milestone, but it is not going into EOS Dawn 1.0.  It was just addressing that Account History API has logic to support those message types, but we are not currently testing them.

**Comment by heifner** [comment] 2017-09-20 15:18
There are a number of items that need to be added for this.
https://github.com/EOSIO/Documentation/blob/master/TechnicalWhitePaper.md#role-based-permission-management

Currently reviewing what additional functionality is required to provide the role-based permission management.

**Comment by heifner** [comment] 2017-09-20 20:31
- [ ] Add linkauth to eosc. The message type already exists.
- [ ] Add unlinkauth to eosc. The message type already exists.
- [ ] Add updateauth to eosc. The message type already exists.
- [ ] Add deleteauth to eosc. The message type already exists.

**Comment by wanderingbort** [comment] 2017-09-20 21:26
Somehow I missed this when consolidating tasks  into #402

That has links to issues where @bytemaster described the desired interface in `eosc` for managing auths

It seems like we will be stepping on each others toes.  How much work is wasted if we close this issue as a duplicate of #402?

**Comment by heifner** [comment] 2017-09-20 21:34
Closing as duplicate of #402.

**Closed by heifner** 2017-09-20 21:34 UTC
Labels: in progress
