### ISSUE TITLE
Append to index file occurring at wrong position: API nodeos failure since 1.7.2

### ISSUE THREAD

**Issue by ScottSallinen** [EOSIO/eos#7193] opened 2019-04-24 14:53 UTC
We've recently suffered two failures to nodes on EOSIO v1.7.2. In both cases, these nodes are API nodes and handle public traffic, as well as use the history_api plugin. Although the history_api is deprecated, it is likely that the issue will affect other API's as well (such as get_block) so it may be useful to investigate.

The failure scenario begins with looping errors that look like the following:

```
error 2019-04-23T12:08:52.824 thread-0  http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing history.get_transaction
debug 2019-04-23T12:08:52.824 thread-0  http_plugin.cpp:653           handle_exception     ] Exception Details: 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:64 check_index_read
rethrow
    {}
    thread-0  block_log.cpp:289 read_block_by_num
    {"block_num":27593175}
    thread-0  controller.cpp:1980 fetch_block_by_number
warn  2019-04-23T12:09:04.963 thread-0  block_log.cpp:64              check_index_read     ] 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:64 check_index_read
warn  2019-04-23T12:09:04.963 thread-0  block_log.cpp:289             read_block_by_num    ] 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:64 check_index_read
error 2019-04-23T12:09:04.963 thread-0  http_plugin.cpp:652           handle_exception     ] FC Exception encountered while processing history.get_transaction
debug 2019-04-23T12:09:04.963 thread-0  http_plugin.cpp:653           handle_exception     ] Exception Details: 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:64 check_index_read
rethrow
    {}
    thread-0  block_log.cpp:289 read_block_by_num
    {"block_num":27593175}
    thread-0  controller.cpp:1980 fetch_block_by_number
```

When shutting down nodeos, the following message appears:

```
warn  2019-04-23T13:42:40.117 thread-0  block_log.cpp:214             append               ] 3190002 block_log_append_fail: fail to append block to the block log
Append to index file occuring at wrong position.
    {"position":"18446744073709551615","expected":435561376}
    thread-0  block_log.cpp:202 append
warn  2019-04-23T13:42:40.487 thread-0  block_log.cpp:214             append               ] 3190002 block_log_append_fail: fail to append block to the block log
Append to index file occuring at wrong position.
    {"position":"18446744073709551615","expected":435561376}
    thread-0  block_log.cpp:202 append
terminate called after throwing an instance of 'eosio::chain::block_log_append_fail'
```

It is not possible to re-launch nodeos without a replay after this failure, as the database dirty flag is set.

This error is very curious: it is new since 1.7.2, and it appears very unlikely -- it happened on a node with high traffic, and on a node with very little traffic, but not on several other nodes with higher and lower traffic, so it is not clear if it is related to API throughput. 

Some thoughts on cause:
- It may be possible that a specific API call, reading/addressing the block log, is interfering with writing.
- It may be a threading issue.
- It is unlikely to be a memory corruption issue as it happened twice to different nodes, with ECC memory.

**Comment by ScottSallinen** [comment] 2019-04-24 15:12
> What is the value of `ulimit -n` ?

1024 -- the default soft limit. True for all servers, those that failed and those that have not.

**Comment by heifner** [comment] 2019-04-24 15:17
That should be increased to something like 65536 as 1024 is too low and can starve `nodeos` of needed file descriptors.

**Comment by ScottSallinen** [comment] 2019-04-24 15:24
We'll try that, and report back if the issue still occurs.

**Comment by heifner** [comment] 2019-04-24 15:24
It is possible that 1.7.2 is more acceptable to this starvation as it handles requests quicker which allows it to consume more file descriptors.

**Comment by matthewdarwin** [comment] 2019-04-24 15:31
I ran out of file descriptors on 1.7.2 earlier this week when my disk I/O went through the roof due to some other unrelated activity and everything slowed to a crawl.... nodeos wouldn't shutdown and had to restore from backup.  (no history or anything fancy enabled).

**Comment by heifner** [comment] 2019-04-24 21:47
Fixed by #7199

**Comment by heifner** [comment] 2019-05-06 17:17
This is fixed in 1.7.3. Please open new issue if you see this in 1.7.3+

**Closed by heifner** 2019-05-06 17:17 UTC
Labels: bug

**Comment by applesauc3** [comment] 2019-05-07 23:36
experienced same issue in 1.7.3-1

**Comment by heifner** [comment] 2019-05-07 23:52
@applesauc3 Can you provide your log?

**Comment by applesauc3** [comment] 2019-05-08 05:01
```
info  2019-05-07T19:28:15.501 thread-0  producer_plugin.cpp:1597      produce_block        ] Produced block 000a1f5ef7b47ed4... #663390 @ 2019-05-07T19:28:15.500 signed by eosio [tr
xs: 0, lib: 663389, confirmed: 0]
warn  2019-05-07T19:28:16.002 thread-0  block_log.cpp:205             append               ] 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:205 append
warn  2019-05-07T19:28:16.002 thread-0  producer_plugin.cpp:1542      maybe_produce_block  ] 13 St13__ios_failure: basic_ios::clear: iostream error
rethrow basic_ios::clear: iostream error:
    {"what":"basic_ios::clear: iostream error"}
    thread-0  block_log.cpp:205 append
warn  2019-05-07T19:28:16.500 thread-0  producer_plugin.cpp:1542      maybe_produce_block  ] 3020000 fork_database_exception: Fork database exception
committed block did not become the new head in fork database
    {}
    thread-0  controller.cpp:683 commit_block
warn  2019-05-07T19:28:16.500 thread-0  producer_plugin.cpp:1131      start_block          ] 3060000 database_exception: Database exception
db revision is not on par with head block
    {"db.revision()":663390,"controller_head_block":663391,"fork_db_head_block":663391}
    thread-0  controller.cpp:1109 start_block
error 2019-05-07T19:28:16.500 thread-0  producer_plugin.cpp:1429      schedule_production_ ] Failed to start a pending block, will try again later
warn  2019-05-07T19:28:16.551 thread-0  producer_plugin.cpp:1131      start_block          ] 3060000 database_exception: Database exception
db revision is not on par with head block
    {"db.revision()":663390,"controller_head_block":663391,"fork_db_head_block":663391}
    thread-0  controller.cpp:1109 start_block
```

**Comment by applesauc3** [comment] 2019-05-08 17:29
producing blocks and running state history plugin, ulimit -n 1048576

**Comment by applesauc3** [comment] 2019-05-08 17:33
attempting to reproduce but nothing yet. was looking through the change and the error and hunch is something around https://github.com/EOSIO/eos/pull/7199/files#diff-5fe104cf373746bc2b06b9f5d57b1aa9R182

also curious why reopen is kinda hacky close open close open with new RW mode https://github.com/EOSIO/eos/pull/7199/files#diff-5fe104cf373746bc2b06b9f5d57b1aa9R56

**Comment by heifner** [comment] 2019-05-08 17:37
The "hacky" close open close open came up in peer review as well. It is there in case the file doesn't exist, the first one will create it while the second one would not. That is only called on startup and a corner case on shutdown.

**Comment by applesauc3** [comment] 2019-05-08 17:38
lsof did not indicate any runaway file descriptors

**Comment by heifner** [comment] 2019-05-08 17:39
I've only seen that error when out of file descriptors, but you may have hit something else.
