### ISSUE TITLE
Build failed Ubuntu 18.04.2 LTS (Windows 10)

### ISSUE THREAD

**Issue by younhajo88** [EOSIO/eos#7524] opened 2019-06-21 01:12 UTC
How do I fix the problem?

Build failed Ubuntu 18.04.2 LTS

![fail](https://user-images.githubusercontent.com/39249723/59890697-1340a480-940d-11e9-8d71-0435e77706f8.png)

**Comment by spoonincode** [comment] 2019-06-21 17:22
Can you try the `develop` branch? I believe this issue is fixed there and I want to be sure before potentially backporting the fix.

**Comment by NorseGaud** [comment] 2019-06-22 02:22
Develop looks to have the issue https://buildkite.com/EOSIO/eosio-base-images/builds/272

**Comment by taokayan** [comment] 2019-06-27 03:12
Please see https://github.com/EOSIO/eos/issues/7490

**Comment by spoonincode** [comment] 2019-06-28 14:43
> Develop looks to have the issue https://buildkite.com/EOSIO/eosio-base-images/builds/272

I don't see anything in that build related to this issue?

**Comment by NorseGaud** [comment] 2019-07-01 21:28
Sorry, posted to the wrong issue; ignore me

**Comment by spoonincode** [comment] 2019-07-02 17:20
closing as dupe of #7490

**Closed by spoonincode** 2019-07-02 17:20 UTC
Labels: Support, build
