### ISSUE TITLE
Add parameters for multi-sig contract actions to cleos

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2255] opened 2018-04-09 03:45 UTC
In order to use the multisig contract currently the user must use cleos to send an action to the contract by building up the proper JSON string.  Add a “propose” option to cleos to make this simpler for users.  Any other actions in the multisig contract should have corresponding cleos options.

**Comment by moskvanaft** [comment] 2018-04-17 16:50
Duplicate of #2163

**Comment by dhaneshvb** [comment] 2018-04-18 01:45
Duplicates to https://github.com/EOSIO/eos/pull/2427

**Closed** 2018-05-09 13:54 UTC
Labels: duplicate, needs testing - pass
