### ISSUE TITLE
Failed to connect to nodeos at http://nodeosd:8888; is nodeos running?

### ISSUE THREAD

**Issue by PaulRBerg** [EOSIO/eos#3145] opened 2018-05-16 21:22 UTC
I carefully followed the instructions from https://github.com/EOSIO/eos/blob/master/Docker/README.md

The containers are successfully running, but when I type `cleos get info` I get the message from the title. Also localhost on port 8888 doesn't work.

These are the logs after running `docker-compose up -d`:
```
pc-199-166:Docker paulrberg$ docker-compose up -d
Starting docker_builder_1 ... done
Starting docker_nodeosd_1 ... done
docker_keosd_1 is up-to-date
pc-199-166:Docker paulrberg$ 
```

**Comment by grigio** [comment] 2018-05-19 15:35
I think it's duplicate of #3018

**Comment by Eenae** [comment] 2018-06-09 08:40
There is a bug in case `keosd` is running not on local machine for all keosd-related commands.

For example, see https://github.com/EOSIO/eos/blob/v1.0.2/programs/cleos/main.cpp#L2191
Before issuing a call to `keosd`, `cleos` is trying to check if it's running (using `try_port` function). It uses correct port extracted from `--wallet-url` option, but completely ignores host specified in `--wallet-url`.

I think in case of remote keosd this check should not be performed.

**Comment by andriantolie** [comment] 2018-07-20 09:05
Yes, there is outdated information by the time this issue is opened. It's already fixed by a PR on June 15 https://github.com/EOSIO/eos/pull/3865

**Closed by andriantolie** 2018-07-20 09:05 UTC
