### ISSUE TITLE
can't set latest master version bios contract to latest version blockchain.

### ISSUE THREAD

**Issue by swang-b1** [EOSIO/eos#8640] opened 2020-02-13 07:40 UTC
I started a blockchain using current master version code, and try to compile latest eosio.contract project get latest contracts. 

When I am trying to set bios contract I got symble unresolvable error 

`➜  bin git:(master) ✗ ./cleos set contract eosio ../../../eosio.contracts/build/contracts/eosio.bios
Reading WASM from /Users/spww/Projects/eosio.contracts/build/contracts/eosio.bios/eosio.bios.wasm...
Publishing contract...
Error 3070000: WASM Exception
Error Details:
env.set_proposed_producers_ex unresolveable`

blockchain info:

`{
  "server_version": "0775c543",
  "chain_id": "cf057bbfb72640471fd910bcb67639c22df9f92470936cddc1ade0e2f2e7dc4f",
  "head_block_num": 1140,
  "last_irreversible_block_num": 1139,
  "last_irreversible_block_id": "00000473ff1c1df134fd20503697f435f9fe093f0095d742d129240c3243e4af",
  "head_block_id": "00000474346af4feb4b86abec81d381381554b77c32c37dd3959dfacffe74053",
  "head_block_time": "2020-02-13T07:39:46.000",
  "head_block_producer": "eosio",
  "virtual_block_cpu_limit": 624015,
  "virtual_block_net_limit": 3276198,
  "block_cpu_limit": 199900,
  "block_net_limit": 1048576,
  "server_version_string": "v2.0.0",
  "fork_db_head_block_num": 1140,
  "fork_db_head_block_id": "00000474346af4feb4b86abec81d381381554b77c32c37dd3959dfacffe74053",
  "server_full_version_string": "v2.0.0-0775c5436033b93e17f78b72b7eb0d04359df2ff-dirty"
}
`

**Comment by heifner** [comment] 2020-02-13 12:30
There is currently a rather complicated process. See: https://developers.eos.io/welcome/latest/tutorials/bios-boot-sequence

**Comment by heifner** [comment] 2020-02-13 12:31
@lparisc Maybe add a little something about that error so people can search docs for it.

**Comment by heifner** [comment] 2020-02-13 12:32
Duplicate of #7990

**Comment by cppfuns** [comment] 2020-02-14 01:20
This article can help solve the problem
https://www.bcskill.com/index.php/archives/884.html

**Comment by lparisc** [comment] 2020-02-25 06:17
[docs/01_nodeos/08_troubleshooting/index.md](https://github.com/EOSIO/eos/tree/docs/2.0.x-add-troubleshooting-item)

**Closed by lparisc** 2020-02-25 06:17 UTC
Labels: documentation
