### ISSUE TITLE
nodeos crashing on occupied listener port of net_plugin

### ISSUE THREAD

**Issue by tochotta** [EOSIO/eos#7909] opened 2019-09-13 20:04 UTC
Run the following command twice from different terminals:
$nodeos -d ./data --config-dir ./config --contracts-console

Problem:
warn  2019-09-13T20:01:45.870 thread-0  controller.cpp:432            initialize_blockchai ] Initializing new blockchain with genesis state
info  2019-09-13T20:01:46.402 thread-0  chain_plugin.cpp:982          plugin_startup       ] starting chain in read/write mode
info  2019-09-13T20:01:46.402 thread-0  chain_plugin.cpp:986          plugin_startup       ] Blockchain started; head block is #1, genesis timestamp is 2018-06-01T12:00:00.000
./02-nodeos.sh: line 17: 31060 Segmentation fault: 11  $vg $nodeos -d ./data --config-dir ./config --contracts-console

Solution:
Proper error handling if bind of listener socket fails.

Test:
Run nodeos twice and on second time it should exit with proper error message.

**Comment by heifner** [comment] 2019-09-13 20:42
What version of eosio? I'm unable to reproduce with 1.8.3.

**Comment by tochotta** [comment] 2019-09-13 21:21
Saw it on latest release/1.8.x  d87164fb71a10695828d29cffe79b2155056da46
as well as on master 7116e88775aa335004e68a66951a682ee933074f

**Comment by heifner** [comment] 2019-09-13 21:23
I tested that commit of 1.8.3, what platform?

**Comment by tochotta** [comment] 2019-09-13 21:38
MACOS

**Comment by heifner** [comment] 2019-09-13 21:54
Yes, using `acceptor->set_option(tcp::acceptor::reuse_address(true));`
I tested on Ubuntu 18.10. I'll test mac on Monday.

**Comment by tochotta** [comment] 2019-09-13 22:08
If it's of any help, I've sent a valgrind.log on Telegram.

**Comment by heifner** [comment] 2019-09-17 00:37
Fixed by #7931

**Closed by heifner** 2019-09-17 00:37 UTC
