### ISSUE TITLE
1.8rc2 runs into an endless loop at startup

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eos#7452] opened 2019-06-03 17:15 UTC
It's probably related to #7420.

While running 1.8rc2 (installed from deb) on Ubuntu-18.04, I enabled producer_api_plugin and produced a snapshot. Then I stopped nodeos, but probably it stopped uncleanly. Upion start, it reported unclean database.

After that I started it from the snapshot it produced. First it detected corrupted state history archive and restored it. Then it went into an infinite loop, not opening any TCP sockets. if I stop and start nodeos again, it keeps looping, occupying 100% of CPU. 

I'm collecting the data archive, will post a link here.

**Comment by cc32d9** [comment] 2019-06-03 17:31
Once I finish archiving the data, I'll try starting it without ship

**Comment by cc32d9** [comment] 2019-06-04 08:21
Here, 800GB archive: http://apiv2.light.xeos.me/eosio_issiue_7452.tar.gz

**Comment by cc32d9** [comment] 2019-06-04 08:24
fi I start it without state history plugin, it's looping as well, so it seems to be not linked to ship

**Comment by spoonincode** [comment] 2019-06-07 02:06
When does it "loop"? Immediately? I'm not able to reproduce so far

**Comment by ssinyagin** [comment] 2019-06-08 08:06
yes, immediately after starting from this state file, it just did nothing but load the CPU at 100%

**Comment by cc32d9** [comment] 2019-06-08 08:09
yes, immediately after starting from this state file, it just did nothing but load the CPU at 100%

**Comment by spoonincode** [comment] 2019-07-09 16:21
Looked at this some today and breaking in to nodeos with a debugger shows it doing a replay. Not entirely clear why there is no output to console indicating as such. Going to remove the support tag since it appears reproducible issue.

**Comment by ndcgundlach** [comment] 2019-07-31 16:22
Using the following test script: 

With no data directory and a configuration jungle-config.ini:

...
plugin = eosio::chain_api_plugin
plugin = eosio::state_history_plugin
plugin = eosio::net_api_plugin
plugin = eosio::producer_plugin
plugin = eosio::producer_api_plugin
plugin = eosio::http_plugin

...

./nodeos -c jungle-config.ini  --disable-replay-opts --chain-state-history --genesis-json ~/genesis.json 

curl http://127.0.0.1:8888/v1/producer/create_snapshot

killall -9 nodeos

./nodeos -c jungle-config.ini  --disable-replay-opts --chain-state-history

{this will fail}

rm -rf state
rm -rf blocks

./nodeos -c jungle-config.ini  --disable-replay-opts --chain-state-history --snapshot /home/developer/.local/share/eosio/nodeos/data/snapshots/snapshot-{snapshot #}.bin 

ps -C nodeos

top -H -p {nodeos pid}

When running v1.8.0-rc2:
    nodeos spins up to ~100% CPU utilization and never spins back down

When running from head of release/v1.8.x (7addcfbd) or develop (7ac04657):
    nodeos spins up to ~100% CPU utilization, but does back off to ~30%

**Comment by spoonincode** [comment] 2019-10-02 18:28
@cc32d9 the logging.json in your archive is set to output error messages only. As far as I can tell, nodeos is working correctly in that it has started a replay it's just not logging any information.

It is a bit unfortunate that logging doesn't initialize its configuration until `main()` which allows some non-error messages to leak through. That could have given the appearance that info level messages are expected.

**Comment by spoonincode** [comment] 2019-10-06 19:42
Going to close this out since it appeared to be a logging.json issue

**Closed by spoonincode** 2019-10-06 19:42 UTC
