### ISSUE TITLE
[help ]"Loading the Bios Contract" failed

### ISSUE THREAD

**Issue by Danilo0120** [EOSIO/eos#4660] opened 2018-07-15 05:37 UTC
@jgiszczak  
when I try the command:   ~/eos$ cleos set contract eosio build/contracts/eosio.bios -p eosio

A ERROR oucur:  
   Reading WAST/WASM from build/contracts/eosio.bios/eosio.bios.wasm...
Using already assembled WASM...
Publishing contract...
1524520ms thread-0   main.cpp:2756                 main                 ] Failed with error: Assert Exception (10)

I have add http-validate-host = false to my nodeos config.ini    but the ERROR still remain.

**Comment by yang24201** [comment] 2018-07-16 03:13
Same error

**Comment by Danilo0120** [comment] 2018-07-16 05:21
I solve it. after you follow the guide below,   you should kill the "keosd" and use the command:"pkill node". and then you use "keosd --http-server-address=127.0.0.1:8900" and "./nodeos -e -p eosio --plugin eosio::wallet_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --replay-blockchain"

good luck for you!

**Comment by Danilo0120** [comment] 2018-07-16 05:21
@yang24201

**Comment by andriantolie** [comment] 2018-07-16 06:54
Seems the problem is solved. I'm closing the issue

**Closed by andriantolie** 2018-07-16 06:54 UTC
