### ISSUE TITLE
Producer plugin should schedule deferred transactions

### ISSUE THREAD

**Issue by wanderingbort** [EOSIO/eos#1841] opened 2018-03-26 15:19 UTC
When deferred transactions were implemented there was no consensus one when producers would attempt to schedule deferred transactions.  As such, our test cases are the only place where deferred transactions are actually scheduled for deliver.  A well-behaved producer should attempt to schedule deferred transactions in an appropriate place.  The producer plugin should facilitate this by offering at least one option for scheduling deferred transactions.

There are many possible options:
 - beginning a new block
 - ending a block (risky due to deadlines)
 - after N pushed transactions (where N could be 1
 - etc
 - all of the above.

**Comment by moskvanaft** [comment] 2018-03-28 22:49
duplicate of #1853

**Closed by moskvanaft** 2018-03-28 22:49 UTC
Labels: duplicate
