### ISSUE TITLE
DAWN-696 ⁃ Guard against indeterministic WASM behavior w.r.t. stack size

### ISSUE THREAD

**Issue by blockone-syncclient** [EOSIO/eos#1757] opened 2018-03-22 20:25 UTC
There is indeterministic (and, divergent based on WASM runtime used) runtime behavior in WASM based on the WASM stack size. Think of, say, a recursive function in WASM. The binaryen runtime will stop execution after a stack depth of 250 calls. However, the WAVM runtime is harder to predict because function locals are placed on to the native stack (it will likely be at a depth of greater than 250).

There must be deterministic behavior in the maximum WASM stack size.

**Comment by bytemaster** [comment] 2018-03-22 22:32
The official standard will be set by the Binaryen version; therefore, the WAVM version should be updated to match.  Because we are only supporting Binaryen in June, this is not a priority for RC1

**Comment by arhag** [comment] 2018-05-03 13:35
Duplicate of #2260 which is now closed.

**Closed by arhag** 2018-05-03 13:35 UTC
Labels: HARDFORK
