### ISSUE TITLE
Connection reset by peer And Connection timed out

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eos#4235] opened 2018-06-20 08:58 UTC
I want to synchronize the data of EOS main network，But I don't know where to find the p2p-peer-address that can be connected。I tried to get it from https://eosnodes.privex.io/, but did not find it can be connected.

**Comment by SoYouDie** [comment] 2018-06-20 13:39
Duplicate of https://github.com/EOSIO/eos/issues/4135

**Closed** 2018-06-21 00:00 UTC
