### ISSUE TITLE
multi-index bug?

### ISSUE THREAD

**Issue by zshchou** [EOSIO/eos#1832] opened 2018-03-26 07:22 UTC
## abi:
```json
"tables": [
    {
      "name": "account",
      "type": "account",
      "index_type": "i64",
      "key_names": ["name1"],
      "key_types": ["account_name"]
    }
  ]
```
## code:
```c++
struct account {
  account_name name1; // 
  account_name name2; //
  uint64_t count;     //
  auto primary_key() const { return name1; }
  EOSLIB_SERIALIZE(account, (name1)(name2)(count))
}

typedef multi_index<N(account), account> account_table;
```
## error:
use cleos get table ...
the row data is confusion.

## fix
```c++
EOSLIB_SERIALIZE(account, (name2)(count))
```
use cleos get table ...
the result is ok! why?

**Comment by jeremi** [comment] 2018-03-27 03:07
I think this is a duplicate of #1742

**Closed** 2018-03-27 16:25 UTC

**Comment by andriantolie** [comment] 2018-04-04 07:35
Duplicate. Since #1742 pass, I will put the pass label here too
