### ISSUE TITLE
build error on mac 10.12.6

### ISSUE THREAD

**Issue by foxundermoon** [EOSIO/eos#1013] opened 2017-12-29 10:09 UTC
```
/Users/fox/workspace/blockchain/eos/libraries/fc/src/crypto/crc.cpp:538:23: warning: unused variable 'crc_c' [-Wunused-const-variable]
static const uint32_t crc_c[256] = {
                      ^
1 warning generated.
[ 43%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/city.cpp.o
In file included from /Users/fox/workspace/blockchain/eos/libraries/fc/src/log/gelf_appender.cpp:5:
In file included from /Users/fox/workspace/blockchain/eos/libraries/fc/include/fc/log/gelf_appender.hpp:3:
/Users/fox/workspace/blockchain/eos/libraries/fc/include/fc/log/appender.hpp:6:42: error: definition of type 'io_service' conflicts with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /Users/fox/workspace/blockchain/eos/libraries/fc/src/log/gelf_appender.cpp:5:
/Users/fox/workspace/blockchain/eos/libraries/fc/include/fc/log/gelf_appender.hpp:7:42: error: definition of type 'io_service' conflicts with typedef of the same name
namespace boost { namespace asio { class io_service; } }
                                         ^
/usr/local/include/boost/asio/io_service.hpp:27:20: note: 'io_service' declared here
typedef io_context io_service;
                   ^
In file included from /Users/fox/workspace/blockchain/eos/libraries/fc/src/log/gelf_appender.cpp:5:
/Users/fox/workspace/blockchain/eos/libraries/fc/include/fc/log/gelf_appender.hpp:31:10: warning: 'initialize' overrides a member function but is not marked 'override'
      [-Winconsistent-missing-override]
    void initialize(boost::asio::io_service& io_service);
         ^
/Users/fox/workspace/blockchain/eos/libraries/fc/include/fc/log/appender.hpp:44:23: note: overridden virtual function is here
         virtual void initialize( boost::asio::io_service& io_service ) = 0;
                      ^
[ 43%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/crypto/base36.cpp.o
1 warning and 2 errors generated.
make[2]: *** [libraries/fc/CMakeFiles/fc.dir/src/log/gelf_appender.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [libraries/fc/CMakeFiles/fc.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by comtechnet** [comment] 2017-12-29 10:40
Looks like a prereq issues (boost library) - make sure your xcode and brew are updated as per the instructions.  Xcode may be "waiting" on you to approve the update/reboot, etc.

**Comment by jgiszczak** [comment] 2017-12-29 16:42
Duplicate of issue #984.  Fixed in master as of this morning.

**Closed by jgiszczak** 2017-12-29 16:42 UTC
