### ISSUE TITLE
Account History API plugin is not enabled!

### ISSUE THREAD

**Issue by lelence** [EOSIO/eos#3006] opened 2018-05-13 14:17 UTC
ubuntu 16.04 and MacOS the same issue, eosio/dawn-v4.0.0

config.ini plugins like : 

plugin = eosio::wallet_api_plugin
plugin = eosio::chain_api_plugin
plugin = eosio::net_api_plugin
plugin = eosio::net_plugin
plugin = eosio::http_plugin
plugin = eosio::producer_plugin
plugin = eosio::history_api_plugin

when i use command "cleos get accounts EOS7m18oUFy3EEUMHepiHbiHpkseGM1LNTY3Du3MNLooUsVzQCQ41"

response is ： 

Error 3110003: Missing Account History API Plugin
Error Details:
Account History API plugin is not enabled

**Comment by onecool2** [comment] 2018-05-13 16:43
yes, I face the same issue, I suppose EOS doesn't support this command anymore  in Dawn4.0.0,

**Comment by tbfleming** [comment] 2018-05-13 17:03
Duplicate of #2876

**Closed** 2018-05-14 01:56 UTC
