### ISSUE TITLE
error: unknown type name 'checksum256'

### ISSUE THREAD

**Issue by hu272293309** [EOSIO/eos#6230] opened 2018-11-05 01:48 UTC
code show as below：

#include <utility>
#include <vector>
#include <string>
#include <cmath>
#include <eosiolib/eosio.hpp>
#include <eosiolib/asset.hpp>
#include <eosiolib/contract.hpp>
#include <eosiolib/crypto.h>
#include <eosiolib/transaction.hpp>

uint128_t _hash(string key) {
            checksum256 result;
            sha256(&key[0], key.size(), &result);
            uint128_t my_number = 0;
            for(char i = 0; i < 32; i++) {
                my_number = my_number + pow(10, i) * result.hash[i];
            }
            return my_number;
        };
  string _transaction_id() {
    checksum256 h;
    auto size = transaction_size();
    char buf[size];
    uint32_t read = read_transaction( buf, size );
    eosio_assert( size == read, "read_transaction failed");
    sha256(buf, read, &h);
    return checksum256_to_string(h);
  }

Why？
eosio.cdt v1.3.2

**Comment by taokayan** [comment] 2018-11-06 09:15
Please use ```capi_checksum256``` instead. If you have further question please ask in https://eosio.stackexchange.com/

**Comment by opcheese** [comment] 2018-11-07 15:01
We have the very same issue: our contract works with checksum256 datatype. We strongly believe that is an erroneous behavior (bug). We would also like to be informed on any developments concerning this issues. As such can this issue please be reopened until the solution is found? At the very least we will be able to post here any useful info regarding reproducing this bug.

**Comment by tbfleming** [comment] 2018-11-07 15:38
It looks like there will be a fix shortly. As a temporary measure you can use the `capi_checksum256` type in `types.h`. The final solution will have a name without the `capi_` prefix.

**Comment by opcheese** [comment] 2018-11-07 15:56
Thank you! We'll look into it. Please keep us posted regarding the status of this issue.

**Comment by tbfleming** [comment] 2018-11-07 15:59
Reopening so I can remember to post updates. I'm not the one working on the fix.

**Comment by conr2d** [comment] 2018-11-08 09:11
Is this a bug?
In eosio.cdt 1.3.x, `checksum256` was renamed to `capi_checksum256`. This change was intended.
https://github.com/EOSIO/eosio.cdt/blob/master/README.md#eosiolib-c-api

**Comment by tbfleming** [comment] 2018-11-08 11:30
It’s a bug because we intended to provide fully-functioning C++ types wrapping the low-level capi types.

**Comment by tbfleming** [comment] 2018-11-09 13:38
This was fixed in CDT 1.4:

> New type eosio::fixed_bytes<T> and aliases eosio::checksum160/256/512 added as C++ replacements for capi_checksum types.

**Closed by tbfleming** 2018-11-09 13:38 UTC

**Comment by opcheese** [comment] 2018-11-09 15:43
Thank you!
