### ISSUE TITLE
String Index

### ISSUE THREAD

**Issue by gleehokie** [EOSIO/eos#2244] opened 2018-04-09 03:13 UTC

**Comment by brianjohnson5972** [comment] 2018-10-30 17:35
This is a duplicate of #1623 (and there is no information here either)

**Closed by brianjohnson5972** 2018-10-30 17:35 UTC

**Comment by dominic-healid** [comment] 2018-11-30 04:07
Any work around for this? need to add an index with a string type for the searching of texts.

**Comment by arhag** [comment] 2018-11-30 05:06
> Any work around for this? need to add an index with a string type for the searching of texts.

Don't expect native (i.e. intrinsic) support for a string index in EOSIO persistent storage anytime soon.

I strongly suggest you find an alternative design for your smart contract. For example, if you only care about lookup of exact string matches, then you can take a SHA256 hash of the string and store a 256-bit secondary index of that hash digest.

If you need to do actual lexicographical sorting of arbitrary length string, then:

- First, re-evaluate whether you really need this as part of your smart contract or if it is something you can have in an off-chain DB that maps strings to primary keys, as part of the larger infrastructure supporting your application.
- If you decide you really do need this accessible to an on-chain smart contract then there may be ways you can implement it mostly on the WASM side by leveraging the existing database intrinsics, particularly the `db_idx256_*` C intrinsics. However, the implementation is quite involved and its performance and memory efficiency won't be as good as a natively supported string index. I won't get into the possible implementations here in this issue. Again, I strongly recommend figuring out if an alternative like the hash solution described above can work for your particular application.

**Comment by dominic-healid** [comment] 2018-12-03 03:15
@arhag Thank you for your response.

I'm trying to follow your suggestion but I'm confuse to what exact data type should I use for this? You mentioned 256-bit, can you provide a sample?

**Comment by arhag** [comment] 2018-12-03 03:34
@dominic-healid:

I don't know of a very good existing example specific to what you are trying to do. 

But you can first take a look at how `eosio::setabi` action in the reference system contract handles taking a SHA256 hash of the ABI byte string and storing the digest in a table:

https://github.com/EOSIO/eosio.contracts/blob/v1.5.1/eosio.system/include/eosio.system/native.hpp#L71-L77

https://github.com/EOSIO/eosio.contracts/blob/v1.5.1/eosio.system/src/eosio.system.cpp#L269-L282

However, there are two important things to note about that example.

First, it is using the old `capi_checksum256` C struct rather than the new [`eosio::checksum256`](https://github.com/EOSIO/eosio.cdt/blob/v1.4.1/libraries/eosiolib/fixed_bytes.hpp#L349) C++ type that was recently added in eosio.cdt. I recommend using the `eosio::checksum256` type in the table rather than `capi_checksum256`, and you can generate the `eosio::checksum256` from the SHA256 hash of arbitrary data (like your string) using the C++ [`eosio::sha256` function](https://github.com/EOSIO/eosio.cdt/blob/v1.4.1/libraries/eosiolib/crypto.hpp#L155).

Second, it doesn't use the SHA256 digest as a 256-bit secondary key in the `multi_index` table, which you would need to do if you want to do lookups by the digest.

You can see an example of using a 256-bit secondary key in the old identity contract:

https://github.com/EOSIO/eos/blob/v1.4.4/contracts/identity/common.hpp#L23-L45

https://github.com/EOSIO/eos/blob/v1.4.4/contracts/identity/common.hpp#L64-L66

Except you would want to use the `eosio::checksum256` rather than the now deprecated `eosio::key256`.
