### ISSUE TITLE
RAM bug

### ISSUE THREAD

**Issue by KenjiroAI** [EOSIO/eos#4517] opened 2018-07-06 06:46 UTC
Hi, I have buy/sell RAM from RAM market without problem for a week but today I have facing with RAM bug.

`{"code":500,"message":"Internal Service Error","error":{"code":3080001,"name":"ram_usage_exceeded","what":"account using more than allotted RAM usage","details":[]}}`

My ram quota is 2113715 bytes and I want to sell just 8192 bytes.

I have report it to EOS Authority, and Rohan get in to help me.

I ask Rohan to get my account info from their API endpoint. He say I have 2MB of RAM which I said above. I have create new signed transaction to sell 8196 bytes RAM and send to Rohan to submit to the network and he also get the same error result.

Rohan said "Just say, Rohan @EOSAuthority looked into it and we both couldn’t figure out what the issue was…"

He also say it might be something around here
https://github.com/EOSIO/eos/blob/4d90af7fce073d5024f2648631088824379c700b/libraries/chain/resource_limits.cpp#L182

I have also try to manual create transaction by eosjs, EOSToolkit, FeeXplorer. All those tools show I have 2MB and I can't sell even if 8192 bytes.

I have try many API endpoint and it's not working.

If anyone want my signed transaction to get proof that it's bug. You can add my telegram `kenjiroai`

**Comment by JohnnyZhao** [comment] 2018-07-06 07:52
could you please provide your account?

**Comment by KenjiroAI** [comment] 2018-07-06 07:57
@JohnnyZhao Could you please add my telegram again? I have set new privacy.

**Comment by JohnnyZhao** [comment] 2018-07-06 08:04
still couldnt add you, add me on telegram: zhaoyu

**Comment by redsung** [comment] 2018-07-06 08:09
I am facing same problem now.

**Comment by jonnyhsy** [comment] 2018-07-06 08:14
![image](https://user-images.githubusercontent.com/1220361/42367673-d21b51ce-80b9-11e8-8199-275d7aaedd9c.png)
 Account eosio.ram has used up almost 100% of its ram, maybe the issue is related to this?

**Comment by KenjiroAI** [comment] 2018-07-06 08:14
@JohnnyZhao OK, Added
@redsung You can't sell any amount of ram, right? Could you please add me in telegram? We will discuss more details about this

**Comment by littlekfc** [comment] 2018-07-06 08:16
@KenjiroAI Please add me as well. My telegram : jirao

**Comment by spartucus** [comment] 2018-07-06 08:19
Do you have enough EOS in your account for ramfee?

There is an `INLINE_ACTION_SENDER` which require ramfee. see [here](https://github.com/EOSIO/eos/blob/master/contracts/eosio.system/delegate_bandwidth.cpp#L197-L200).

```
if( fee > 0 ) {
    INLINE_ACTION_SENDER(eosio::token, transfer)( N(eosio.token), {account,N(active)},
    { account, N(eosio.ramfee), asset(fee), std::string("sell ram fee") } );
}
```

**Comment by KenjiroAI** [comment] 2018-07-06 08:23
@jonnyhsy Might be not because it affect only some account
@littlekfc Added
@spartucus I think It reduce from amount of sell not from my account because I have always all in RAM before without any problem.

**Comment by KenjiroAI** [comment] 2018-07-06 08:41
@dhaneshvb  Why you close this issue? My problem is not solve yet. Many people facing with this problem.

**Comment by d553296416** [comment] 2018-07-06 08:43
Why closed......

**Comment by spartucus** [comment] 2018-07-06 08:49
Hi @KenjiroAI, that's weird,  from what i have known, if inline action fails, the transaction fails too, please correct me if i am wrong. 

reference [here](https://github.com/EOSIO/eos/wiki/Smart-Contract#inline-communication).

>Inline communication takes the form of requesting other actions that need to be executed as part of the calling action. Inline actions operate with the same scopes and authorities of the original transaction, and are guaranteed to execute with the current transaction. These can effectively be thought of as nested transactions within the calling transaction. If any part of the transaction fails, the inline actions will unwind with the rest of the transaction. Calling the inline action generates no notification outside the scope of the transaction, regardless of success or failure.

**Comment by paritygeeker** [comment] 2018-07-06 09:04
So the error may be from here:
```
eosio.system/delegate_bandwidth.cpp:191
INLINE_ACTION_SENDER(eosio::token, transfer)( N(eosio.token), {N(eosio.ram),N(active)},
                                                       { N(eosio.ram), account, asset(tokens_out), std::string("sell ram") } );
```
I will try on local private eos node.

**Comment by dhaneshvb** [comment] 2018-07-06 09:11
Closed by mistake, sorry about that. Reopened

**Comment by jonnyhsy** [comment] 2018-07-06 09:30
@KenjiroAI I think it's totally possible, see the two lines of code @paritygeeker referenced, eosio.ram account needs to transfer system tokens.  

To explain why some succeeded but some failed - eosio.ram's ram usage actually fluctuates as ppl buy/sell rams...

**Comment by KenjiroAI** [comment] 2018-07-06 09:38
Wow! I'm not expecting it to happen this way.

@spartucus  Confirm, the bug is from INLINE_ACTION_SENDER as you said and I can sell it before might be as @jonnyhsy explain.

Thanks :)

**Comment by taokayan** [comment] 2018-07-06 10:03
one possible reason is that your account doesn't have any EOS. If yes, try to transfer some (0.0001 EOS) then do sellram again.

**Comment by d553296416** [comment] 2018-07-06 10:10
thanks, I transferred some eos to my account fix this

**Comment by KenjiroAI** [comment] 2018-07-06 10:11
@taokayan Yeah, the problem solved. Should we set infinity RAM for eosio.ram?

**Closed** 2018-07-06 10:10 UTC
Labels: bug

**Comment by taokayan** [comment] 2018-07-06 10:12
Not really. The balance row memory usage should be paid by the user instead of eosio.ram, this is similar to "steal" RAM from eosio.ram.

**Comment by wujunchuan** [comment] 2018-07-19 17:16
Does that fee not get taken after the ram is sold ?
I guess they should take a fee after the sales not before?
Anyone can tell me? What's the acctually order?
