### ISSUE TITLE
Compile issue on v.1.8.0-rc1

### ISSUE THREAD

**Issue by HuweyII** [EOSIO/eos#7251] opened 2019-05-02 01:04 UTC
This is a fresh VM, running Ubuntu 18.04LTS

Last bit of compile looks like this
`[ 77%] Building CXX object libraries/fc/CMakeFiles/fc.dir/src/compress/zlib.cpp.o

In file included from /export/vol01/v1.8.0-rc1/libraries/fc/src/compress/zlib.cpp:3:0:
/export/vol01/v1.8.0-rc1/libraries/fc/src/compress/miniz.c: In function ‘void tdefl_find_match(tdefl_compressor*, mz_uint, mz_uint, mz_uint, mz_uint*, mz_uint*)’:
/export/vol01/v1.8.0-rc1/libraries/fc/src/compress/miniz.c:2290:5: warning: this ‘if’ clause does not guard... [-Wmisleading-indentation]
     if (!dist) break; q = (const mz_uint16*)(d->m_dict + probe_pos); if (TDEFL_READ_UNALIGNED_WORD(q) != s01) continue; p = s; probe_len = 32;
     ^~
/export/vol01/v1.8.0-rc1/libraries/fc/src/compress/miniz.c:2290:23: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the ‘if’
     if (!dist) break; q = (const mz_uint16*)(d->m_dict + probe_pos); if (TDEFL_READ_UNALIGNED_WORD(q) != s01) continue; p = s; probe_len = 32;
                       ^

[ 77%] Linking CXX static library libfc.a
[ 77%] Built target fc
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2`

**Comment by spoonincode** [comment] 2019-05-02 15:50
The excerpt you pasted appears to only be a warning. You may need to scroll further back to find the error.

**Comment by spoonincode** [comment] 2019-05-05 19:16
possibly #7260

**Comment by NorseGaud** [comment] 2019-05-07 15:12
zlib isn't installing properly due to a build script error:
The script has `if [ ! -d $OPT_LOCATION/zlib || $FORCE_BUILD ]; then` which is wrong. I've got a fix in for this in https://github.com/EOSIO/eos/pull/7285

**Comment by NorseGaud** [comment] 2019-05-07 18:49
@HuweyII Are you certain you've done a `git submodule update --init --recursive --force` and can replicate the error?

**Comment by andriantolie** [comment] 2019-06-26 09:39
I've tried using a fresh AWS instance with Ubuntu18.04 and I can confirm that this issue can be replicated in 1.8.0-rc1. On another fresh AWS instance with Ubuntu18.04, I can also confirm that this issue has been fixed in 1.8.0-rc2, so @HuweyII please try again with 1.8.0-rc2. I'm going to close this issue. Thanks.

**Closed by andriantolie** 2019-06-26 09:39 UTC
