### ISSUE TITLE
cleos get table "more" returns true if records match query

### ISSUE THREAD

**Issue by infohata** [EOSIO/eos#4942] opened 2018-07-31 09:20 UTC
`cleos get table account account table --limit 10` returns `"more":true` when there are just 10 records in the table, but with `--limit 11` it returns `"more": false`. In other words, if --limit matches the query result rows count, it returns false positive for "more".

**Comment by taokayan** [comment] 2018-07-31 10:11
This is by design. "more" means whether or not there's more data than the returning result.

**Comment by infohata** [comment] 2018-08-02 12:12
and this is exactly what I am reporting. It is reporting false positive extra data when there aren't any. If result exactly matches query, it reports that there is "more":true when it's not. Please reopen, reproduce, and fix.

**Comment by infohata** [comment] 2018-08-02 12:13
@sergmetelin bump

**Comment by jgiszczak** [comment] 2018-08-02 22:52
Confirmed off-by-one error.

**Comment by aclark-b1** [comment] 2020-07-31 18:49
In order to focus our efforts on issues that are currently creating difficulty for the community we are closing tickets that were created prior to the EOSIO 2.0 release.  If you believe this issue is still relevant please feel free to reopen it or create a new one.  Thank you for your continued support of EOSIO!

**Closed by aclark-b1** 2020-07-31 18:49 UTC
Labels: needs review
