### ISSUE TITLE
multisig exec error with authority

### ISSUE THREAD

**Issue by giniz** [EOSIO/eos#2702] opened 2018-05-02 08:21 UTC
I run all steps of the eosio.multisig described in README.md and got this error at the execution step:

_cleos multisig exec tester test -p tester
Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"treasury","permission":"active"}', but does not have signatures for it._

In the wallet, already had tester@active and treasury@active
cleos get account tester
_{
  "account_name": "tester",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}_

cleos get account treasury
_{
  "account_name": "treasury",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}_

**Comment by imoonstal** [comment] 2018-05-03 09:05
Ensure your wallet is unlock. "./cleos wallet list" command can display your wallet status.
"default *",* means that the wallet is unlock.
"./cleos wallet unlock -n WALLET_NAME --password YOUR_WALLET_PASSWORD" command can unlock the wallet.

**Comment by giniz** [comment] 2018-05-04 01:26
thank @imoonstal,
But my wallet was unlocked already. I followed the tutorial of multisig step by step so to reach the multisig exec step my wallet was opened and unlocked at previous step.
I have tried with _default_ and _custom_ wallet, both failed.

**Comment by giniz** [comment] 2018-05-04 09:02
I tried with another but still got that issue

```
eos_env$ mcleos multisig exec stock netting1 stock -p stock
Error 3030002: signatures do not satisfy declared authorizations
Ensure that you have the related private keys inside your wallet and your wallet is unlocked.
Error Details:
transaction declares authority '{"actor":"stock","permission":"active"}', but does not have signatures for it.
eos_env$ mcleos get account stock
{
  "account_name": "stock",
  "permissions": [{
      "perm_name": "active",
      "parent": "owner",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    },{
      "perm_name": "owner",
      "parent": "",
      "required_auth": {
        "threshold": 1,
        "keys": [{
            "key": "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
            "weight": 1
          }
        ],
        "accounts": []
      }
    }
  ]
}
eos_env$ mcleos wallet keys | grep EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV
    "EOS6MRyAjQq8ud7hVNYcfnVPJqcVpscN5So8BhtHuGYqET5GDW5CV",
```

**Comment by giniz** [comment] 2018-05-08 01:17
hi @imoonstal , just to confirm whether the issue belongs to my machine or not.
Have you run multisig tutorial successfully yet?

**Comment by zhaoxingjie** [comment] 2018-05-17 02:58
i got the same mistake too, still cant configure it.

**Comment by OuterSpaceTears** [comment] 2018-05-31 08:37
i got the same mistake too.

**Comment by kristieguo** [comment] 2018-06-14 05:52
I have the same problem

**Comment by taokayan** [comment] 2018-06-19 07:50
Can you provide the command that you used for "propose" and "approve"? And any other commands that you did to reproduce the issue?

**Comment by andriantolie** [comment] 2018-07-19 03:11
Yes, the fact that the list of provided_approvals is not the subset of requested_approvals seems peculiar to me. Can you please provide the command requested by @taokayan above?

**Comment by srmcatee1110** [comment] 2018-09-02 18:34
Any update or fix to this.  I have been able to repeat the same error.  Review and everything else works.  

Kinda a show stopper for EOS.

**Comment by srmcatee1110** [comment] 2018-09-12 00:35
I did the following lines to propose.  I am using the hello contract.  I still get the same error as above.

`cleos multisig propose payme '[{"actor": "consumer", "permission": "active"},{"actor": "merchant", "permission": "active"}]' '[{"actor": "merchant", "permission": "active"}]' fimulti hi '{"user":"nesha"}' -p merchant@active

#cleos multisig review merchant payme
#cleos multisig approve merchant payme4 '{"actor": "merchant", "permission": "active"}' -p merchant@active
#cleos multisig approve merchant payme4 '{"actor": "consumer", "permission": "active"}' -p consumer@active
`

**Comment by andriantolie** [comment] 2018-10-30 06:28
@giniz we haven't received any response from your for quite some time and this issue is already quite outdated so I'm going to close this issue. 
If you still have the problem and wish to discuss further, please post it in https://eosio.stackexchange.com. To keep things organized, Github issues are intended for bugs reporting and features tracking, and Stack Exchange is the right place for any technical support discussions. Thanks!

@srmcatee1110 try to see @taokayan recommendation first, seems to me it's a different problem from the original issue. If you still have a problem, please post it in Stack Exchange. Thanks!

**Closed by andriantolie** 2018-10-30 06:28 UTC
Labels: Support
