### ISSUE TITLE
can we change prefix keys, like public key started with EOS ?

### ISSUE THREAD

**Issue by mark11226** [EOSIO/eos#10017] opened 2021-02-08 06:36 UTC
Hello. I am facing some issue regarding EOSIO,
issue #9977  and #10000 is not helpful , can  someone tell me detailed solution ?
I have forked EOS Blockchain

Now, i need to change the public key which is starting which EOS,
I have forked EOS Blockchian, now i need to change public key starting like if it is the key

EOS7XsgKKCP6UrRFoNMA8qB2bs5A9Z1darasuH6wWq3HM5tSgoABR

what i want is, I have to change it to my Name whaterver i have like,

AAA7XsgKKCP6UrRFoNMA8qB2bs5A9Z1darasuH6wWq3HM5tSgoABR

Can any body help me in that. Thanks in advance.

**Comment by aclark-b1** [comment] 2021-02-10 18:25
Closing as this is a duplicate of #10021

**Closed by aclark-b1** 2021-02-10 18:25 UTC
