### ISSUE TITLE
EOS does not support IPv6

### ISSUE THREAD

**Issue by centromere** [EOSIO/eos#11037] opened 2022-01-19 21:59 UTC
The `--http-server-address` flag does not support IPv6.

```
error 2022-01-19T21:56:31.543 nodeos    http_plugin.cpp:745           plugin_initialize    ] failed to configure http to listen on [...::...]:8888 (resolve: Service not found)
```

https://github.com/EOSIO/eos/blob/8f29da1845c1f1a3479bc32dce0238e9873a8bf4/plugins/http_plugin/http_plugin.cpp#L739

**Comment by praphael** [comment] 2022-01-19 22:05
IPv6 is not supported as this time.  
This is a duplicate of 
https://github.com/EOSIO/eos/issues/8169

**Closed as completed by praphael** 2022-01-19 22:05 UTC
