### ISSUE TITLE
eosd fails to start after some period of time.

### ISSUE THREAD

**Issue by pavybez** [EOSIO/eos#328] opened 2017-09-04 06:28 UTC
How to replicate:
1. start eosd. 
2. create some accounts
3. create some contracts
4. push some messages
5. kill eosd
6. wait for ~30 minutes.
7. start eosd

Error is as below:

![image](https://user-images.githubusercontent.com/7913634/30014160-5ebcb208-917d-11e7-81d4-c6e2ea9fe943.png)

**Comment by pavybez** [comment] 2017-09-04 06:39
This could be because the process was shutdown inappropriately. But still the process should be able to restart.

**Comment by learnforpractice** [comment] 2017-09-04 06:51
It was caused by an improper shutdown of process.

Eosd need to improve its database consistency.

Use rm -rf data-dir/blockchain/ to walk around this problem.

**Comment by bytemaster** [comment] 2017-09-04 19:14
How did you kill eosd?  

^C should do a clean shutdown.  

Will look into other ways of signal clean shutdown.

**Comment by pavybez** [comment] 2017-09-07 05:19
I killed it using kill -9 <pid>.

**Comment by pmesnier** [comment] 2017-09-07 05:23
That's a really heavy hammer. When you have multiple instances you can kill them all with 
pkill eosd
and give them some time to shut down cleanly.

**Comment by pmesnier** [comment] 2017-09-07 05:31
The built in signal handler traps SIGINT (2) and SIGTERM (15) to do orderly shutdowns. 
If you start the eosd with the launcher, you can use launcher -k [signum] to terminate all that it started.

**Comment by heifner** [comment] 2017-10-18 17:21
Kill -9 not supported at the moment without a resync or replay. Closing.

**Closed by heifner** 2017-10-18 17:21 UTC
