### ISSUE TITLE
cleos wallet error //Invalid content-length response

### ISSUE THREAD

**Issue by nunettine** [EOSIO/eos#4637] opened 2018-07-13 10:30 UTC
![image](https://user-images.githubusercontent.com/39987149/42687170-10760c10-86d3-11e8-8a9d-258cba743ba6.png)
![image](https://user-images.githubusercontent.com/39987149/42687194-20399d60-86d3-11e8-8c67-45ff50876090.png)

i use ubuntu 16.04 , i reinstall today , but i see error that i did't see 
any advise...?

**Comment by spartucus** [comment] 2018-07-13 10:33
I believe it's a duplicate of https://github.com/EOSIO/eos/issues/4594.

add `http-validate-host = false` to your config.ini of keosd, restart keosd.

**Comment by skostic9242** [comment] 2018-07-13 12:57
also having same issue... i'm not using docker, installed it via script, nodeos and keosd are working, but i get same error with cleos... i put http-validate-host = false in config.ini of nodeos, where is config.ini of keosd?

**Comment by skostic9242** [comment] 2018-07-13 14:42
i managed to fix it by running nodeos and keosd on different ports, and wallet create works, but now publishing account fails with same error...

**Comment by nunettine** [comment] 2018-07-14 03:52
i used docker, but cinfig.ini of keosd is not exist , 
i find two of config.ini , docker,build 
i change docker_config.ini, but i can't solve it

**Comment by kitchenSpoon** [comment] 2018-07-15 01:31
Im using docker and encountering the same error, I can't find where is config.ini to change `http-validate-host = false`

**Comment by jadhavajay** [comment] 2018-07-15 13:37
It's into `/tmp/eosio/config` directory ...

**Comment by peterokwara** [comment] 2018-07-15 19:46
![screenshot from 2018-07-15 22-38-53](https://user-images.githubusercontent.com/6847405/42737675-015430dc-8880-11e8-871d-59f1772341cb.png)
For docker, I added the flag here and it worked :-)

**Comment by vijaytabhatt** [comment] 2018-07-18 05:34
@peterokwara  where to find this file in which i have to write --http-validate-host=false ?
i start eosiod using 

> sudo docker run --rm --name eosio -d -p 8888:8888 -p 9876:9876 -v /tmp/work:/work -v /tmp/eosio/data:/mnt/dev/data -v /tmp/eosio/config:/mnt/dev/config eosio/eos-dev  /bin/bash -c "nodeos -e -p eosio --plugin eosio::wallet_api_plugin --plugin eosio::wallet_plugin --plugin eosio::producer_plugin --plugin eosio::history_plugin --plugin eosio::chain_api_plugin --plugin eosio::history_api_plugin --plugin eosio::http_plugin -d /mnt/dev/data --config-dir /mnt/dev/config --http-server-address=0.0.0.0:8888 --access-control-allow-origin=* --http-validate-host=false --contracts-console"

>  cleos --wallet-url http://127.0.0.1:8888 wallet create works 
   but cleos wallet create does not work

**Comment by vijaytabhatt** [comment] 2018-07-18 09:13
@peterokwara  thanks using above command worked!
1) I am using instructions given at https://developers.eos.io/eosio-nodeos/docs/docker-quickstart  , are those correct?
2) i understand http://localhost:8888 as i have run nodeos on port 8888 , but why do we have to give wallet-url of 8900? is it the default port?

can you just explain me use of the above commands , one is used to start nodeos using docker then we start cleos on that nodeos instance

sorry if i am asking basic questions but i need to understand use of this function

**Comment by peterokwara** [comment] 2018-07-18 09:18
@vijaytabhatt do you have telegram? Search for @skypee on telegram then I tell you how it works

**Comment by dixia** [comment] 2018-11-01 06:14
hi @nunettine  @vijaytabhatt please refer to this page https://developers.eos.io/eosio-nodeos/docs/cleos-overview on the developer portal. Any other problem feel free to post at EOS.IO stack exchange https://eosio.stackexchange.com/

**Closed by dixia** 2018-11-01 06:14 UTC
Labels: Support
