### ISSUE TITLE
eosd -> Segmentation fault: 11  on Mac OS Sierra 10.12.6

### ISSUE THREAD

**Issue by eluzgin** [EOSIO/eos#469] opened 2017-09-16 15:32 UTC
Successfully built EOS project. 
Then ran built eosd binary - got Segmentation fault: 11 error 
No config created.

**Comment by eluzgin** [comment] 2017-09-17 14:35
Switched to Ubuntu 16, built without any errors and ran single node.

**Comment by staticinstance** [comment] 2017-09-17 18:12
I'm getting the same issue on Mac OS Sierra 10.12.6, I'll look into switching to Ubuntu 16.  However, it would be interesting to know the solution to this.

**Comment by staticinstance** [comment] 2017-09-17 21:23
Up and running with Ubuntu

**Comment by pavybez** [comment] 2017-09-18 01:29
How are you running eosd? I tried and am unable to reproduce issue.

**Comment by staticinstance** [comment] 2017-09-18 21:22
./eosd

**Comment by pavybez** [comment] 2017-09-19 02:01
Can you delete the data-dir folder and try again?

**Comment by staticinstance** [comment] 2017-09-19 09:40
I managed to get it to run on Mac OS Sierra 10.12.6  
I updated xcode and updated the config.ini and pointed genesis-json to the genesis.json file in the build directory

**Comment by pavybez** [comment] 2017-09-20 02:57
Great. I will close the issue then and reopen if you encounter it again.

**Closed by pavybez** 2017-09-20 02:57 UTC
